serilog/serilog-aspnetcore

README.md, samples/SimpleWebSample/Program.cs, src/Serilog.AspNetCore/Serilog.AspNetCore.csproj
* #1 - option to configure inline so that default configuration/hosting context information is available
=> 2.1.0 Release

samples/SimpleWebSample/Program.cs, samples/SimpleWebSample/appsettings.json
PR for [issue 17](https://github.com/serilog/serilog-aspnetcore/issues/17).
Some updating for sampe.
=> Update for SimpleWebSample

src/Serilog.AspNetCore/AspNetCore/SerilogLoggerFactory.cs
I needed to retrieve some configuration prior to registering the logger. `UseSerilog` is invoked before the `Startup` class. I sought to register the Factory manually but found out that is internal. I think that `SerilogLoggerFactory` is the main take away from this library and therefore exposing it would make it more flexible for those who don't want to use the extension methods.
=> Expose `SerilogLoggerFactory`

README.md
`Serilog.Settings.Configuration` needs to be installed for the delegate configuration example to work.
=> Added information about the Serilog.Settings.Configuration package

samples/EarlyInitializationSample/Controllers/HomeController.cs, samples/EarlyInitializationSample/Program.cs, samples/EarlyInitializationSample/Startup.cs, samples/EarlyInitializationSample/appsettings.json, samples/InlineInitializationSample/Controllers/HomeController.cs, samples/InlineInitializationSample/Program.cs, samples/InlineInitializationSample/Startup.cs, samples/InlineInitializationSample/appsettings.json, src/Serilog.AspNetCore/AspNetCore/RequestCompletionMiddleware.cs, src/Serilog.AspNetCore/AspNetCore/SerilogLoggerFactory.cs, src/Serilog.AspNetCore/RequestLoggingOptions.cs, src/Serilog.AspNetCore/Serilog.AspNetCore.csproj, src/Serilog.AspNetCore/SerilogApplicationBuilderExtensions.cs, src/Serilog.AspNetCore/SerilogWebHostBuilderExtensions.cs
This long-talked-about feature adds middleware for request logging, based on the popular sample in [this blog post](https://blog.datalust.co/smart-logging-middleware-for-asp-net-core/).
In comparison with the default request logging performed by the framework, this implementation condenses as much information as possible into a single event, resulting in easier correlation and lower log volumes.
An example completion event might look like:
```
[15:31:09 INF] HTTP GET / responded 200 in 13.8298 ms {"RequestId": "0HLNOCKKFBOL3:00000003",
"CorrelationId": null, "ConnectionId": "0HLNOCKKFBOL3"}
```
(I'm using the `{Properties:j}` output formatting option to include properties not present in the log message itself. This makes the events a bit noisier, but it's easier to see what's going on.) …
=> UseSerilogRequestLogging()

README.md, samples/EarlyInitializationSample/Controllers/HomeController.cs, samples/InlineInitializationSample/Controllers/HomeController.cs, src/Serilog.AspNetCore/AspNetCore/RequestCompletionMiddleware.cs, src/Serilog.AspNetCore/Serilog.AspNetCore.csproj
Updated to use the latest _Serilog.Extensions.Hosting_; describe request logging in the README.
=> README and dependency updates

src/Serilog.AspNetCore/AspNetCore/RequestLoggingMiddleware.cs
=> Adding source context for the logging in RequestLoggingMiddleware. 

README.md
The current documentation recommends overriding the logging level for the entire Microsoft namespace, but this also suppresses logging for other Microsoft products, such as Entity Framework Core. Suggest updating this to recommend overriding Microsoft.AspNetCore instead.
=> Update docs on disabling built-in logging

src/Serilog.AspNetCore/AspNetCore/RequestLoggingMiddleware.cs, src/Serilog.AspNetCore/AspNetCore/RequestLoggingOptions.cs, src/Serilog.AspNetCore/SerilogApplicationBuilderExtensions.cs
Follows on from #132, includes request timing information in the level computation.
=> Include 'double elapsedMs' in the function signature of the GetLevel delegate

README.md, samples/EarlyInitializationSample/Startup.cs, samples/InlineInitializationSample/Startup.cs, src/Serilog.AspNetCore/AspNetCore/RequestLoggingMiddleware.cs, src/Serilog.AspNetCore/AspNetCore/RequestLoggingOptions.cs
Add RequestHost & RequestScheme to log properties and list all options in docs
=> Add RequestHost & RequestScheme to log properties

src/Serilog.AspNetCore/AspNetCore/RequestLoggingMiddleware.cs
LogCompletion event was not including properties added via
`EnrichDiagnosticContext` delegate on options because
the properties had been collected before invoking the enricher.
Swapping the order of the statements fixes this.
This is a fix for https://github.com/serilog/serilog-aspnetcore/issues/148
I'm afraid I haven't had time to add a test for this. I have built the package locally and tested it with the project I am currently working on.
=> FIX: Enrich context before collecting properties

README.md
Fixes #147 
The instructions for using Serilog contained statements that were no longer valid since .NET Core 3.0 uses the Generic Host and new project templates.
The code sample in the readme and the corresponding statements were updated to resemble these changes.
=> Update Instructions for .NET Core 3 templates

global.json
Pin the .NET Core SDK version to the `3.1.1xx` feature band. Do not
allow prerelease versions.
Fixes #175
=> Pin .NET Core SDK version to latest feature band

src/Serilog.AspNetCore/AspNetCore/RequestLoggingMiddleware.cs
When running integration tests using the WebApplicationFactory class, I noticed that the code `httpContext.Features.Get<IHttpRequestFeature>()?.RawTarget` returns an empty string instead of null, which causes the fallback never executing and displaying no path information.
=> Fallback RequestPath for when IHttpRequestFeature.RawTarteg is empty

README.md, global.json, samples/InlineInitializationSample/Program.cs, samples/InlineInitializationSample/Startup.cs, src/Serilog.AspNetCore/Serilog.AspNetCore.csproj
Shows the new `UseSerilog()` inline overload from https://github.com/serilog/serilog-extensions-hosting/pull/20
=> Update to show new UseSerilog() overload including service provider

src/Serilog.AspNetCore/AspNetCore/RequestLoggingMiddleware.cs, src/Serilog.AspNetCore/AspNetCore/RequestLoggingOptions.cs
=> Allow an ILogger to be specified

samples/InlineInitializationSample/Startup.cs, src/Serilog.AspNetCore/AspNetCore/RequestLoggingOptions.cs, src/Serilog.AspNetCore/SerilogApplicationBuilderExtensions.cs, test/Serilog.AspNetCore.Tests/Serilog.AspNetCore.Tests.csproj, test/Serilog.AspNetCore.Tests/SerilogWebHostBuilderExtensionsTests.cs, test/Serilog.AspNetCore.Tests/Support/Extensions.cs, test/Serilog.AspNetCore.Tests/Support/SerilogWebApplicationFactory.cs
It is a common pattern to configure middleware options outside of `Configure(IApplicationBuilder)`. It could be a different module, for example. It also integrates with `Microsoft.Extensions.Options`. This PR will allow such configuration:
```csharp
public void ConfigureServices(IServiceCollection services)
{
services.Configure<RequestLoggingOptions>(Configuration.GetSection("Serilog")); // get MessageTemplate from appsettings.json
services.PostConfigure<RequestLoggingOptions>(options =>
{
options.EnrichDiagnosticContext = (diagnosticContext, httpContext) =>
{
diagnosticContext.Set("RemoteIpAddress", httpContext.Connection.RemoteIpAddress.MapToIPv4());
};
});
}
public void Configure(IApplicationBuilder app)
{
// ..
app.UseSerilogRequestLogging();
app.UseRouting();
// ...
}
```
=> Allow RequestLoggingOptions configuration outside of Configure(IApplicationBuilder)

README.md
=> Docs: Added pushing properties to Readme

src/Serilog.AspNetCore/Serilog.AspNetCore.csproj, test/Serilog.AspNetCore.Tests/SerilogWebHostBuilderExtensionsTests.cs
Just updates the version of _Serilog.Extensions.Hosting_ to 4.1.0 and re-enables the target.
Will need some basic testing on .NET Framework (there's none in the test project here, currently), but should otherwise be ready to roll into #235
=> Re-enable .NET Framework support through netstandard2.0

src/Serilog.AspNetCore/Serilog.AspNetCore.csproj, src/Serilog.AspNetCore/SerilogWebHostBuilderExtensions.cs
This PR re-enable build against .NetCore 3.1 and .Net 5. Resolves #239
=> Drop Microsoft.AspNetCore.Http.Abstractions for netcoreapp3.1 and higher

Build.ps1, README.md, appveyor.yml, src/Serilog.AspNetCore/Serilog.AspNetCore.csproj
* #240 - Drop _Microsoft.AspNetCore.Http.Abstractions_ dependency for `netcoreapp3.1` and higher
* #242 - bump .NET SDK version to avoid depending on a vulnerable ASP.NET framework version
=> 4.1.0 Release

README.md
`LogEventLevel.Information` requires `using Serilog.Events;`
=> Add using statement to readme example

src/Serilog.AspNetCore/Serilog.AspNetCore.csproj
We are trying to use some of the latest functionalities from `Serilog.Settings.Configuration`. It would be good to use the transitive dependency instead of forcing the latest manually.
I reckon this is a fairly safe PR. Let me know if I need to add something else.
=> Bump Serilog.Settings.Configuration to latest version (3.3.0)

src/Serilog.AspNetCore/AspNetCore/RequestLoggingMiddleware.cs, src/Serilog.AspNetCore/Serilog.AspNetCore.csproj, test/Serilog.AspNetCore.Tests/SerilogWebHostBuilderExtensionsTests.cs
Fixes: serilog/serilog-aspnetcore#270
Depends on: https://github.com/serilog/serilog-extensions-hosting/pull/56
- `RequestLoggingMiddleware.LogCompletion` enriches with the exception set in `IDiagnosticContext`, unless an unhandled exception takes precedence.
- Add tests on enriching with collected exception and favoring unhandled exception
- Functionally tested and Serilog request log event is correctly enriched with exception set in `IDiagnosticContext`
=> Log exception set in IDiagnosticContext

src/Serilog.AspNetCore/Serilog.AspNetCore.csproj
https://github.com/serilog/serilog-extensions-hosting/releases/tag/v5.0.1
=> Update to fixed Serilog.Extensions.Hosting version 5.0.1

src/Serilog.AspNetCore/Serilog.AspNetCore.csproj
Updates _Serilog.Extensions.Hosting_ to [5.0.1](https://github.com/serilog/serilog-extensions-hosting/releases/tag/v5.0.1)
=> 6.0.1 Release

src/Serilog.AspNetCore/AspNetCore/RequestLoggingMiddleware.cs, src/Serilog.AspNetCore/AspNetCore/RequestLoggingOptions.cs, test/Serilog.AspNetCore.Tests/SerilogWebHostBuilderExtensionsTests.cs
=> Add GetMessageTemplateProperties option

Directory.Build.props, global.json, samples/Sample/Controllers/HomeController.cs, samples/Sample/Models/ErrorViewModel.cs, samples/Sample/Program.cs, samples/Sample/Sample.csproj, samples/Sample/Startup.cs, serilog-aspnetcore.sln, src/Serilog.AspNetCore/AspNetCore/RequestLoggingMiddleware.cs, src/Serilog.AspNetCore/AspNetCore/RequestLoggingOptions.cs, src/Serilog.AspNetCore/AspNetCore/SerilogLoggerFactory.cs, src/Serilog.AspNetCore/Serilog.AspNetCore.csproj, src/Serilog.AspNetCore/SerilogApplicationBuilderExtensions.cs, src/Serilog.AspNetCore/SerilogWebHostBuilderExtensions.cs, test/Serilog.AspNetCore.Tests/Serilog.AspNetCore.Tests.csproj, test/Serilog.AspNetCore.Tests/SerilogWebHostBuilderExtensionsTests.cs, test/Serilog.AspNetCore.Tests/Support/DisposeTrackingLogger.cs, test/Serilog.AspNetCore.Tests/Support/Extensions.cs, test/Serilog.AspNetCore.Tests/Support/SerilogSink.cs, test/Serilog.AspNetCore.Tests/Support/SerilogWebApplicationFactory.cs
also
* file scoped namespaces
* move common settings to props
=> enable nullable

Directory.Build.props, README.md, appveyor.yml, global.json, samples/Sample/Controllers/HomeController.cs, samples/Sample/Models/ErrorViewModel.cs, samples/Sample/Program.cs, samples/Sample/Sample.csproj, samples/Sample/Startup.cs, serilog-aspnetcore.sln, src/Serilog.AspNetCore/AspNetCore/RequestLoggingMiddleware.cs, src/Serilog.AspNetCore/AspNetCore/RequestLoggingOptions.cs, src/Serilog.AspNetCore/AspNetCore/SerilogLoggerFactory.cs, src/Serilog.AspNetCore/Serilog.AspNetCore.csproj, src/Serilog.AspNetCore/SerilogApplicationBuilderExtensions.cs, src/Serilog.AspNetCore/SerilogWebHostBuilderExtensions.cs, test/Serilog.AspNetCore.Tests/Serilog.AspNetCore.Tests.csproj, test/Serilog.AspNetCore.Tests/SerilogWebHostBuilderExtensionsTests.cs, test/Serilog.AspNetCore.Tests/Support/DisposeTrackingLogger.cs, test/Serilog.AspNetCore.Tests/Support/Extensions.cs, test/Serilog.AspNetCore.Tests/Support/SerilogSink.cs, test/Serilog.AspNetCore.Tests/Support/SerilogWebApplicationFactory.cs
* #305 - add `GetMessageTemplateProperties` option (@dnperfors)
* #306 - language level modernization and cleanup (@SimonCropp)
=> 6.1.0 Release

src/Serilog.AspNetCore/Serilog.AspNetCore.csproj
Update the version of `Serilog.Settings.Configuration` to 3.4.0 to remove dependency on out of date upstream package.  
Resolves #311
=> Update Serilog.Settings.Configuration to latest version.

samples/Sample/Program.cs, samples/Sample/Sample.csproj, src/Serilog.AspNetCore/AspNetCore/RequestLoggingMiddleware.cs, src/Serilog.AspNetCore/Serilog.AspNetCore.csproj, test/Serilog.AspNetCore.Tests/SerilogWebHostBuilderExtensionsTests.cs
Reported in: https://github.com/serilog/serilog-aspnetcore/issues/207#issuecomment-1756844594
The dependencies and their versions here are temporary, we'll soon be updating this package to .NET 8 and will ideally RTM the upstream pieces then, too.
=> Collect trace and span ids in request completion events

README.md
=> Fix properties example to use LogContext

src/Serilog.AspNetCore/Serilog.AspNetCore.csproj
Update Microsoft.AspNetCore.Hosting.Abstractions and Microsoft.AspNetCore.Http.Abstractions to 2.3.0
Fixes #398
=> Update deprecated NuGet packages Microsoft.AspNetCore.* 
